# Default values for job-executer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "*/5 * * * *"
context: context-tag
chartSelector: wordpress
chartReleaseSelector: my_site_release
suspend: false
image:
  repository: bitnami/kubectl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
restic:
  bunzip2DownloadUrl: https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox_BUNZIP2
  downloadUrl: https://github.com/restic/restic/releases/download/v0.13.1/restic_0.13.1_linux_amd64.bz2
  repository: s3:s3.amazonaws.com/bucket_name/restic
  password: restic-password
  awsAccessKeyId: AWS_ACCESS_KEY_ID
  awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
  forgetOptions: "--keep-last 7 --keep-weekly 5 --prune"
# exemple for bitnami wordpress chart exclude updraft
  backupOptions: "--exclude=/bitnami/wordpress/bin --exclude=/bitnami/wordpress/wp-content/updraft/ /bitnami/wordpress"

# exemple for bitnami wordpress chart backup sql database
beforeBackupScript: |-
 export DATE=$(date +'%m-%d-%Y-%H_%M')
 wp db export "/bitnami/wordpress/"\$DATE".sql"
afterBackupScript: |-
 rm "/bitnami/wordpress/"\$DATE".sql"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
