# Default values for job-executer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Configure the cronjob schedule
schedule: "*/5 * * * *"

# -- Context used to set hostname for backup
context: context-tag
# -- name of the chart (used to select pod)
chartSelector: wordpress
# -- name of the chart release (used to select pod)
chartReleaseSelector: my_site_release
# -- name of the container of the pod (used to select pod)
containerSelector: ""

# -- Suspend cronjob
suspend: false
# -- image used for kubectl command
image:
  # -- repo of image used for kubectl command
  repository: bitnami/kubectl
  # -- pullPolicy of image used for kubectl command
  pullPolicy: IfNotPresent
  # -- tag of image used for kubectl command
  tag: "1.24.1"
# Configure the restic command
restic:
  # -- bzip2 download url to extract restic binary
  bunzip2DownloadUrl: https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox_BUNZIP2
  # -- restic download url to install binary if not present
  downloadUrl: https://github.com/restic/restic/releases/download/v{{.Chart.AppVersion}}/restic_{{.Chart.AppVersion}}_linux_amd64.bz2
  # -- repo location of restic backup
  repository: s3:s3.amazonaws.com/bucket_name/restic
  # -- password of restic backup
  password: restic-password
  # -- s3 config access for restic backup
  awsAccessKeyId: AWS_ACCESS_KEY_ID
  # -- s3 config access for restic backup
  awsSecretAccessKey: AWS_SECRET_ACCESS_KEY
  # -- restic forget options
  forgetOptions: "--keep-last 7 --keep-weekly 5 --prune"
  # -- restic backup options
  backupOptions: "--exclude=/bitnami/wordpress/bin --exclude=/bitnami/wordpress/wp-content/updraft/ /bitnami/wordpress"

# -- custom backup command
customBackupCommand: ""

# -- script executed before backup (do not forget \ before $ if bash variables used)
beforeBackupScript: |-
 export DATE=$(date +'%m-%d-%Y-%H_%M')
 wp db export "/bitnami/wordpress/"\$DATE".sql"
# -- script executed after backup (do not forget \ before $ if bash variables used)
afterBackupScript: |-
 rm "/bitnami/wordpress/"\$DATE".sql"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # -- capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
