apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.name" .}}-config
  namespace: {{ include "template.namespace" .}}
data:
{{- range .Values.containers -}}
{{- if .configMap -}}{{- if and .configMap.environment -}}
  {{- range .configMap.environment }}
  {{ .key }} : "{{ .value }}"
  {{- end }}
{{- end }}{{- end }}
{{- if .configMap -}}{{- if and .configMap.files -}}
  {{- range .configMap.files }}
  {{ .name }}:{{ .content | toYaml | indent 2}}
  {{- end }}
{{- end }}{{- end }}
{{- end }}