# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ include "template.name" .}}-pv
#   namespace: {{ include "template.namespace" .}}
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#   - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: {{ .Values.storage.localStoragePath }}
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - {{ .Values.storage.node }}
