apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: {{ include "template.name" .}}-secret
    namespace: {{ include "template.namespace" . }}
  data:
    {{- with .Values.secrets.containers }}
    {{- if . }}{{- if and .environment }}
      {{- range .environment }}
    {{ .key }} : "{{ .value | b64enc }}"
      {{- end }}
    {{- end }}{{- end }}
    {{- if and . }}{{- if and .files }}
      {{- range .files }}
    {{ .name }}: "{{ .content | b64enc}}"
      {{- end }}
    {{- end }}{{- end }}
    {{- end }}
- apiVersion: v1
  data:
    .dockercfg: "{{ .Values.secrets.dockerConfig | b64enc }}"
  kind: Secret
  metadata:
    name: registry-secret
    namespace: {{ include "template.namespace" . }}
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    tls.crt: "{{ .Values.secrets.tlsCrt | b64enc }}"
    tls.key: "{{ .Values.secrets.tlsKey | b64enc }}"
  kind: Secret
  type: Opaque
  metadata:
    name: https-certificate
    namespace: {{ include "template.namespace" . }}