apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: {{ include "template.name" .}}-secret
    namespace: {{ include "template.namespace" . }}
  data:
    {{- range .Values.containers }}
    {{- if .secrets }}{{- if and .secrets.environment }}
      {{- range .secrets.environment }}
    {{ .key }} : "{{ .value | b64enc }}"
      {{- end }}
    {{- end }}{{- end }}
    {{- if and .secrets }}{{- if and .secrets.files }}
      {{- range .secrets.files }}
    {{ .name }}: "{{ .content | b64enc}}"
      {{- end }}
    {{- end }}{{- end }}
    {{- end }}
- apiVersion: v1
  data:
    .dockercfg: "{{ .Values.secrets.dockerConfig | b64enc }}"
  kind: Secret
  metadata:
    name: registry-secret
    namespace: {{ include "template.namespace" . }}
  type: kubernetes.io/dockercfg
- apiVersion: v1
  data:
    tls.crt: "{{ .Values.secrets.tlsCrt | b64enc }}"
    tls.key: "{{ .Values.secrets.tlsKey | b64enc }}"
  kind: Secret
  type: Opaque
  metadata:
    name: https-certificate
    namespace: {{ include "template.namespace" . }}
- apiVersion: v1
  data:
    REGISTRATION_TOKEN: {{ .Values.secrets.registrationToken }}
  kind: Secret
  type: Opaque
  metadata:
    name: gitlab-secret
    namespace: {{ include "template.namespace" . }}