{{- range .Values.containers -}}
{{- if .service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "template.fullname" $ }}
  namespace: {{ include "template.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ include "template.name" $ }}
    helm.sh/chart: {{ include "template.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "template.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}